spring:
  datasource:
    url: jdbc:mariadb://cksdnr3seoul.cuf07tqldv8k.ap-northeast-2.rds.amazonaws.com:3307/cksdnr3
    driver-class-name: org.mariadb.jdbc.Driver
    username: cksdnr3
    password: duddls!2
  jpa:
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      location: C:\Users\cksdn\dev\project\img
      max-request-size: 100MB
      max-file-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: goodcastingofficial@gmail.com
    password: goodc1234
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
security:
  jwt:
    secret: secret-value

shop:
  goodcast:
    upload:
      path: C:\Users\cksdn\dev\project\img

UserController:
  signup: Create user and returns ins JWT token
  signin: Authenticaties user and returns ins JWT token